backend:
  name: git-gateway
  repo: gwu205/defmc
  branch: main
media_folder: "images/uploads"
publish_mode: editorial_workflow
collections:
  - name: "news"
    label: "News Post"
    folder: "content/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "news"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
